### ISSUE TITLE
SAML10/L11 Erasure programming failed 

### ISSUE THREAD

**Issue by neomissing** [ataradov/edbg#109]
Test programming today and find it doesn't work? Is there a programming problem？

**Comment by ataradov** [comment]
You would need to provide more details. What exactly does not work? What errors you are getting? How are you running the program? What debugger are you using? What target hardware? Howe are you connecting the debugger to the target?

**Comment by neomissing** [comment]
I use IBDAP, Use the following command:edbg -b -t saml11 -pv -f Demo.bin,Has been in Programming......，Won't end.

**Comment by ataradov** [comment]
The part before ',' is erase, which apparently works. The part after is supposed to be programming, which never completes.  I have never seen this happen before. One thing you can try is decrease the clock frequency.

I think I have IBDAP, so I will try that tomorrow.

**Comment by ataradov** [comment]
Ok, there is no ','. Please quote the exact output when reporting bugs.

I can reproduce the issue. It does not depend on the debugger. I see the same behaviour with other debuggers. I'll try to figure out what is wrong.

**Comment by ataradov** [comment]
The issue was related to L11 and its security stuff. It should be fixed now.
