### ISSUE TITLE
unknown target device

### ISSUE THREAD

**Issue by jjwsei** [ataradov/edbg#110]
I'm running Ubuntu 20.04, using an Atmel ICE, and a custom board that has a SAMD20G17A chip on it. The board works great when using arm-none-eabi-gdb but I was trying to use edbg for programming. I have added DSU_DID = 0x10001406 to the target_atmel_cm0p.c, as mentioned in another post. I ran make clean then make all. But when I run **edbg -br -c 48000 -t samd20**, or any other command, I still get the same unknown target error.

**Comment by ataradov** [comment]
You need to add it as 0x10001006. Bits 8-11 represent the device revision, which is masked out when detecting the device.

Also, there is no way it would do 48 MHz clock. It does not matter, since Atmel-ICE itself would not go that fast.
