### ISSUE TITLE
error_exit() function and target reset

### ISSUE THREAD

**Issue by ibrahimdanish** [ataradov/edbg#113]
We have a situation where we are interested only in verifying binaries executing in the target with the one we supply. 
If they are the same we had no issues, if they are different, error_exit() is called by target_verify() and we observe that the target MCU stops executing.

If we add dap_reset_target_hw(1) in error_exit() as shown below, the issue gets resolved.
```
void error_exit(char *fmt, ...)
{
  va_list args;

  if (g_debugger)
  {
    dap_reset_target_hw(1);
    dap_led(0, 0);
    dap_disconnect();
    dbg_close();
  }

  va_start(args, fmt);
  fprintf(stderr, "Error: ");
  vfprintf(stderr, fmt, args);
  fprintf(stderr, "\n");
  va_end(args);

  exit(1);
}
```
Does debugger keep holding the target after disconnect?

**Comment by ataradov** [comment]
Those cleanup steps are a recent addition to the code, so they don't do as much as they could. I've added target reset on all error exits.
