### ISSUE TITLE
Programming ATsaml21e17b

### ISSUE THREAD

**Issue by Srrarr** [ataradov/edbg#118]
Hello,
I was trying to program ATsaml21e17b in linux with Atmel-ICE. I use the following command:
 _./edbg -b -p -v -f Name.hex -t saml21_

I get this output
_Debugger: ATMEL Atmel-ICE CMSIS-DAP J41800115186 1.0 (SJ)
Clock frequency: 16.0 MHz
Error: unknown target device (DSU_DID = 0x1081021a)_

That's this mean I can not use this tool with this micro?

Thanks.

**Comment by ataradov** [comment]
I've added support for this part, it should work now. 

Also, this tool does not support hex files, it only supports raw binary files.

**Comment by Srrarr** [comment]
Thank you very much!
