### ISSUE TITLE
Request to add entry for SAM V70N19 Rev B

### ISSUE THREAD

**Issue by sabunassar** [ataradov/edbg#133]
Thanks for the great tool. Is it possible you could add an entry for the SAM V70N19 Rev B? I was able to add in a local build and have been using it successfully.

  { 0xa13d0a01, 0x00000001, "samv70", "SAM V70N19 (Rev B)",     512*1024 },

Thanks

**Comment by ataradov** [comment]
I've added a generic detection of the device revision and added all the existing devices.
