### ISSUE TITLE
add new part ATSAMD20G18A

### ISSUE THREAD

**Issue by wtelaball** [ataradov/edbg#29]
Hi ataradov,

working perfectly with your tool. Faced a new part that is not currently supported.
ATSAMD20G18A
Debugger: ATMEL EDBG CMSIS-DAP ATML1873060200016987 01.1A.00FB (S)
Error: unknown target device (DSU_DID = 0x10001405)

I believe an added line to .h in cm0p will do the job as stated in the datasheet.

  { 0x10001405, "SAM D20G18A",       0, 256*1024, 64, 4096, 256 },

Good job!

**Comment by ataradov** [comment]
There are a lot of parts not supported. If you want to see your part here - submit a pull request. Changes for new parts are accepted almost automatically.
