### ISSUE TITLE
SAMD21G18

### ISSUE THREAD

**Issue by criticalboot** [ataradov/edbg#40]
Hi
I am using samd21G18A chip, with atmel ice I am trying to burn bootloader to it.  I am getting the following response when using the command. 
`./edbg -t atmel_cm0p`
`Error: invalid response while writing the register 0x00 (count = 0, value = 7)`

what can be the cause for the error.

**Comment by ataradov** [comment]
This can be a lot of thing, starting from a dead device or broken connections.

**Comment by criticalboot** [comment]
Sorry, my bad. broken connections.

after fixing connections I am getting

```
./edbg -e -t atmel_cm0p
Error: unknown target device (DSU_DID = 0x10010306)

```
can you throw some light on this?

**Comment by ataradov** [comment]
You need to add that device in the table of devices in target_atmel_cm0p.c.
Just based on that ID, it would read:

`  { 0x10010306, "SAM D21G18A (Rev E)", 256*1024, 4096 },`

**Comment by criticalboot** [comment]
Thanks, for your help. Now able to upload the program.
