### ISSUE TITLE
Invalid response while writing the register with Atmel CM7 on OS X

### ISSUE THREAD

**Issue by ydesgagn** [ataradov/edbg#48]
Hi,

I'm using edbg to program an Atmel CM7. I'm compiling edbg on Windows and OS X. Initially both are not working as i'm always getting this:

Debugger: ATMEL Atmel-ICE CMSIS-DAP J41800088582 01.27.0082 (SJ)
Error: invalid response while writing the register 0x00 (count = 0, value = 7)

A hardware guy told me that the SWD clock ratio was too high compared with the CPU clock. So I went into Atmel Studio under Tools -> Device Programming and in interface settings I set the SWD clock to 128 kHz (was 2 MHz). When I hit save and go back to edbg I can now program my file on this specific machine only.

How can I do the same on OS X or Linux where Atmel Studio doesn't run?

Any help would be appreciated.

Thanks

**Comment by ataradov** [comment]
This makes no sense. Settings in should have no effect on the operation of this tool. 

You can lower the frequency by setting DAP_FREQ define in edbg.c (16 MHz default, but tools rarely can go this high anyway).

See if this helps first, and if it does not, we'll have to debug more.

**Comment by ydesgagn** [comment]
With DAP_FREQ at 128k it's working well.

Can you add this as a command line parameter?

**Comment by ataradov** [comment]
128K will be very slow. It is strange that setting in the studio affects device operation. Atmel-ICE must be ignoring my value.

I'll add a parameter for that later today.

**Comment by ataradov** [comment]
Added new option '-c' or '--clock'.

**Comment by mraardvark** [comment]
I think the standalone debuggers will store the clock settings between sessions, which is why Studio affects Atmel-ICE.  On-board debuggers do not do this, and revert on reboot (to about 2MHz SWD, I think?)

**Comment by ataradov** [comment]
Yes, but I always unconditionally set 16 MHz (prior to that update). So Atmel-ICE must have ignored that setting, probably because it is higher than it can do. I was setting a really big number, letting debuggers go as fast as they can. Most of them can't go very fast :)

**Comment by ydesgagn** [comment]
All working well. Thank you very much!!!

Closing.
