### ISSUE TITLE
Is it feasible to erase part of flash e.g. -e -z 0x2000

### ISSUE THREAD

**Issue by markfirmware** [ataradov/edbg#67]
@ataradov This ought to speed up the program/test cycle for small programs. Right now it takes more than 8 seconds to erase same70q21 (2MB.) My program is actually smaller than one erase block.

Thanks, Mark

**Comment by ataradov** [comment]
You don't need to erase the whole chip to program a part of the unlocked device. Just drop "-e" and it all will work. The programming algorithm will erase the sectors that are about to be programmed.

"-e" is designed to invoke a very specific behavior - a dedicated Chip Erase command.

**Comment by markfirmware** [comment]
That is good news. Thanks!
