### ISSUE TITLE
ATSAMD21G16L unknown target device ID (after manually adding to target_atmel_cm0p.c)

### ISSUE THREAD

**Issue by Lonney** [ataradov/edbg#79]
I've added what I believe is the correct entry to `target_atmel_cm0p.c` for programming an ATSAMD21G16L device:

```{ 0x10011557, "samd21", "SAM D21G16L",   64*1024 }```

However, when I try and program the device I get the following error:
```bash
Debugger: ATMEL Atmel-ICE CMSIS-DAP J42700001914 01.27.0082 (SJ)
Clock frequency: 16.0 MHz
Error: unknown target device (DSU_DID = 0x10011557)

**Comment by ataradov** [comment]
It has to be added as 0x10011057 to mask out the revision number.
