### ISSUE TITLE
ATSAMD21G16L does not run after a 'successful' program

### ISSUE THREAD

**Issue by Lonney** [ataradov/edbg#80]
After manually adding its entry, programming an `ATSAMD21G16L` with an Atmel-iCE and a hex file (~34kb) _appears_ to work fine, including erasing and verifying.

However, the code on the chip does not run afterwards.

If I program the same device, with an Atmel-iCE, using Atmel Studio 7, with the same hex file, it runs just fine.

Dumping the memory from the device, after either program, reveals that the data is identical up until offset `0x00008420` (around where I expect the end of the hex file data to be).

After that though, the portion of the empty memory is different:

**Dump after EDBG programming**
![edbg_hex](https://user-images.githubusercontent.com/4212320/64551080-343dd500-d32c-11e9-8e57-c168f85c09a1.PNG)

**Dump after Atmel Studio 7 programming**
![atmel_studio_hex](https://user-images.githubusercontent.com/4212320/64551121-46b80e80-d32c-11e9-8f53-36912ffadb06.PNG)

Is there some other option/configuration step I'm missing?

**Comment by ataradov** [comment]
Is this dump of the raw data? This looks like a HEX file, and there is no point in looking at it in a hexadecimal view, it is just a text file. But you need to specify a binary file for the EDBG.

Make sure you specify a binary file as an argument.

**Comment by Lonney** [comment]
Yes, these are reads of the chip flash using `--target samd21 --read dump.hex`.

> Make sure you specify a binary file as an argument.

Do you mean for programming or reading or both?

Reading it with `--target samd21 --read dump.bin` instead gives the same result at the end of the file:
![edbg_bin](https://user-images.githubusercontent.com/4212320/64598217-43b23200-d3af-11e9-8466-07045ad8bf62.png)

Compared with that of the flash from a working chip:
![atmel_bin](https://user-images.githubusercontent.com/4212320/64599223-e4edb800-d3b0-11e9-83ec-2f671a6396af.png)

**Comment by ataradov** [comment]
If reading gives this result, it means you have programmed a HEX file in a first place. And it got interpreted as a binary. 

You need to specify raw binary file for both reading and writing.

**Comment by Lonney** [comment]
Ah, apologies: for some reason I thought I remembered reading that EDBG supported programming with .hex files!

Using a .bin instead works as expected for this device, thank you!
