### ISSUE TITLE
Some DAP_info item may be 0 and descriptor values should be used

### ISSUE THREAD

**Issue by UweBonnes** [ataradov/edbg#84]
Hello,

a MIMXRT1060-EVK return no values for DAP_INFO_VENDOR, DAP_INFO_PRODUCT an info DAP_INFO_SER_NUM. 

As https://arm-software.github.io/CMSIS_5/DAP/html/group__DAP__Info.html states, this is allowed and the descriptor values should be used in that case.

**Comment by ataradov** [comment]
It is good that now there is actual documentation. At the time this code was developed there was none.

I will fix that later this week.

**Comment by ataradov** [comment]
This is addressed in the most recent commit.
