### ISSUE TITLE
PG164140 programmer support?

### ISSUE THREAD

**Issue by staticmem** [ataradov/edbg#95]
I have a Microchip PG164140 programmer coming and intend to use it for the ATSAMC21G17A.
Will the edbg software be able to program it using that programmer and MCU?

If not can you recommend another software.  I use Linux command line.

**Comment by ataradov** [comment]
Only CMSIS-DAP compliant debuggers are supported. PICkit 4 is not one of them.

As far as I know the only software that supports it is the official Microchip software. MPLAB and stuff.
